### ISSUE TITLE
🐛 [BUG] 로그인, 회원가입 버그 발견

### ISSUE THREAD

**Issue by 5kiran** [Nomik94/LounGe#112]
# 🐛 버그/에러 개요

회원가입 인증이메일 발송 불가, 카카오 로그인 토큰 발급이 안됨
# 🚨 상황 설명
### 🩹 에러 대상

인증번호 발송 불가
### 📷 에러 상황

![image](https://user-images.githubusercontent.com/118159013/224388204-234b0991-a40d-4623-b2ed-3fd7305274b8.png)
### ✅ TODO

- [ ] 카카오 로그인 토큰 발급
- [ ] 회원가입 500에러!

**Comment by 5kiran** [comment]
썬더클라이언트로 가입해보니 정상 작동하네요
회원가입은 프론트 문제일까요?

**Comment by Nomik94** [comment]
제 상황에서는 잘 됩니다.
풀리퀘 하나 올려놨으니 코드 리뷰하시고 수락해주신 뒤 풀 받아서 다시 해보시겠어요?
